### ISSUE TITLE
null === $userImage -> Error FigureBuilder

### ISSUE THREAD

**Issue by xprojects-de** [dreibein/contao-author-bundle#4]
Servus zusammen,

erstmal danke für die Erweiterung !

Contao 4.11.6

Bekomme den Fehler "Argument 1 passed to Contao\CoreBundle\Image\Studio\FigureBuilder::fromPath() must be of the type string, null given".

Grund ist da beim Benutzer kein Bild ausgewählt ist (ist na nicht mandatory) und das UserImage === null ist.
Das mag der FigureBuilder nicht :-) welcher ja im AuthorController benutzt wird.

Vielleicht könnt ihr da einen kleinen NULL-Check einbauen.

Danke und Grüße

**Comment by Xirdion** [comment]
Hallo,

vielen Dank für dein Feedback.
Ich habe soeben eine neue Version 1.0.3 des Bundles erstellt, in welcher die Null-Pointer-Exception behoben ist.
